name = "brand-management-api"
main = "src/index.js"
compatibility_date = "2025-01-01"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

# Cloudflare D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "brand-management-db"
database_id = "5006f1b8-8bcd-4780-8e20-3644d4727f6a"
